"""Sets the development of every county in Southern Kallonia at 6355.

Southern Kallonia in 6355 is meant to read as classical antiquity rather than
as a dark age: a network of real cities on the coast and the river mouths, a
worked countryside behind them, and an interior of hills and mountains that the
cities have barely touched. The base game's own 867 start is the yardstick,
where the median county sits at 7 and the greatest cities in the world reach
25 to 30. Nothing here reaches that, because Thenithria has not yet been rebuilt
in white elmin and the continent has never been ruled by one throne.

What a county is worth:

* the ground it sits on, since plains feed a city and mountains do not,
* the sea, since every great city of this age is a port,
* what already stands on it, counting the towns and the temples rather than
  the keeps,
* and whether a realm is seated there, weighted by what kind of realm it is.
  A city state is one city and all of its wealth, so it counts for more than a
  duchy of the same size, and Ketan, which lives on the ledger, counts for most.

Run with --write to put the file into the mod.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.join(HERE, "..")
WRITE = "--write" in sys.argv

names = json.load(io.open(os.path.join(HERE, "names_southern_kallonia.json"), encoding="utf-8"))
asg = json.load(io.open("D:/Patriam-CK3-map/db/assignments/southern_kallonia.json", encoding="utf-8"))
asg = asg.get("data", asg)
faction = {f["key"]: f for f in asg["factions"]}
realm_of = {int(p): faction[k] for p, k in asg["assigned"].items() if k in faction}

prov_src = io.open(os.path.join(MOD, "history", "provinces", "00_patriam_southern_kallonia.txt"),
                   encoding="utf-8-sig").read()
holding = {int(m.group(1)): m.group(2)
           for m in re.finditer(r"^(\d+) = \{[^}]*?holding = ([a-z_]+)", prov_src, re.M | re.S)}

# The counties named in the title history are exactly the seats: each realm's
# ruler is given their top title and the capital county beneath it.
held_src = io.open(os.path.join(MOD, "history", "titles", "00_patriam_titles.txt"),
                   encoding="utf-8-sig").read()
seats = set(re.findall(r"^(c_[a-z0-9_]+) = \{", held_src, re.M))

GROUND = {"plains": 5.5, "hills": 3.0, "mountains": 1.0, "farmlands": 8.0,
          "wetlands": 3.0, "forest": 4.0, "drylands": 3.0, "desert": 1.0}
SEAT = {"kingdom": 5.5, "duchy": 3.0, "house": 1.5, "county": 1.5, "city state": 6.0}
KETAN = 8.5

size = {}
for pid, realm in realm_of.items():
    size[realm["name"]] = size.get(realm["name"], 0) + 1

rows = []
for k in names:
    for d in k["duchies"]:
        for c in d["counties"]:
            bars = c["baronies"]
            seat_bar = bars[0]
            realm = realm_of.get(seat_bar["province"], {})

            ground = sum(GROUND.get(b.get("terrain", "plains"), 4.0) for b in bars) / len(bars)

            coast = 0.0
            if seat_bar.get("coastal"):
                coast += 2.0
            share = sum(1 for b in bars if b.get("coastal")) / float(len(bars))
            coast += 1.5 * share

            built = 0.0
            for b in bars[1:]:
                kind = holding.get(b["province"])
                if kind == "city_holding":
                    built += 1.2
                elif kind == "church_holding":
                    built += 0.8
                elif kind == "castle_holding":
                    built += 0.4
            built = min(built, 3.0)

            # The seat of a realm carries the realm, so it carries its weight too.
            seat = 0.0
            if realm and c["key"] in seats:
                seat = KETAN if realm["name"] == "Ketan" else SEAT.get(realm["tier"], 1.5)
                seat += min(3.0, size.get(realm["name"], 0) / 30.0)

            dev = ground + coast + built + seat
            dev = int(round(max(1.0, min(20.0, dev))))
            rows.append((c["key"], c["name"], dev, realm.get("name", ""), realm.get("tier", "")))

rows.sort()
out = ["\ufeff############################################################",
       "# Patriam: Rise of Empires. What every county is worth in 6355.",
       "#",
       "# Southern Kallonia in this age is a classical one. The coast and the river",
       "# mouths carry real cities, the ground behind them is worked, and the hills",
       "# and the mountains are barely touched. Nothing here reaches the figure the",
       "# base game gives Rome or Constantinople, since Thenithria is not yet built",
       "# in white elmin and no throne has yet held the whole continent.",
       "#",
       "# Generated by tools/build_development.py. Do not hand edit.",
       "############################################################",
       ""]
for key, name, dev, realm, tier in rows:
    note = "%s, %s" % (realm, tier) if realm else "unclaimed"
    out.append("%s = { # %s. %s" % (key, name, note))
    out.append("\t6355.1.1 = { change_development_level = %d }" % dev)
    out.append("}")

devs = sorted(r[2] for r in rows)
print("counties: %d  min %d  median %d  mean %.1f  max %d"
      % (len(devs), devs[0], devs[len(devs) // 2], sum(devs) / float(len(devs)), devs[-1]))
import collections
print("spread:", sorted(collections.Counter(devs).items()))
print("the ten richest:")
for key, name, dev, realm, tier in sorted(rows, key=lambda r: -r[2])[:10]:
    print("  %2d  %-26s %s (%s)" % (dev, name, realm, tier))
print("the five poorest:")
for key, name, dev, realm, tier in sorted(rows, key=lambda r: r[2])[:5]:
    print("  %2d  %-26s %s (%s)" % (dev, name, realm, tier))

path = os.path.join(MOD, "history", "titles", "01_patriam_development.txt")
text = "\n".join(out) + "\n"
if WRITE:
    io.open(path, "w", encoding="utf-8", newline="\n").write(text)
    print("written", path, len(text), "bytes")
else:
    print("dry run, would write", path, len(text), "bytes")
